import type { Recipe } from './types';

/**
 * Mock recipe data for testing and development
 */
export const mockRecipes: Recipe[] = [
  {
    id: '1',
    user_id: 'user-1',
    title: 'Pasta Pomodoro with Basil',
    description: 'Classic Italian pasta with fresh tomatoes and basil',
    thumbnail_url:
      'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&h=600&fit=crop',
    cooking_time: 15,
    servings: 2,
    categories: [],
    ingredients: [],
    steps: [],
  },
  {
    id: '2',
    user_id: 'user-1',
    title: 'Pasta Aglio Olio with Olives',
    description: 'Simple garlic and olive oil pasta with Mediterranean flavors',
    thumbnail_url:
      'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&h=600&fit=crop',
    cooking_time: 15,
    servings: 2,
    categories: [],
    ingredients: [],
    steps: [],
  },
  {
    id: '3',
    user_id: 'user-2',
    title: 'Pasta Bolognese',
    description: 'Rich meat sauce with penne pasta',
    thumbnail_url:
      'https://images.unsplash.com/photo-1598866594230-a7c12756260f?w=800&h=600&fit=crop',
    cooking_time: 15,
    servings: 4,
    categories: [],
    ingredients: [],
    steps: [],
  },
  {
    id: '4',
    user_id: 'user-2',
    title: 'Pasta Carbonara',
    description: 'Creamy Roman pasta with bacon and egg',
    thumbnail_url:
      'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&h=600&fit=crop',
    cooking_time: 15,
    servings: 2,
    categories: [],
    ingredients: [],
    steps: [],
  },
  {
    id: '5',
    user_id: 'user-3',
    title: 'Pasta Alfredo',
    thumbnail_url:
      'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=800&h=600&fit=crop',
    cooking_time: 20,
    servings: 3,
    categories: [],
    ingredients: [],
    steps: [],
  },
  {
    id: '6',
    user_id: 'user-3',
    title: 'Spaghetti Marinara',
    description: 'Fresh seafood pasta with tomato sauce',
    thumbnail_url:
      'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&h=600&fit=crop',
    cooking_time: 25,
    categories: [],
    ingredients: [],
    steps: [],
  },
  {
    id: '7',
    user_id: 'user-4',
    title: 'Pesto Pasta',
    description: 'Vibrant basil pesto with pine nuts',
    thumbnail_url:
      'https://images.unsplash.com/photo-1595295333158-4742f28fbd85?w=800&h=600&fit=crop',
    cooking_time: 10,
    servings: 2,
    categories: [],
    ingredients: [],
    steps: [],
  },
  {
    id: '8',
    user_id: 'user-4',
    title: 'Mushroom Risotto',
    thumbnail_url:
      'https://images.unsplash.com/photo-1476124369491-f51aae654b1d?w=800&h=600&fit=crop',
    cooking_time: 35,
    servings: 4,
    categories: [],
    ingredients: [],
    steps: [],
  },
  {
    id: '9',
    user_id: 'user-5',
    title: 'Caesar Salad',
    description: 'Crispy romaine with parmesan and croutons',
    thumbnail_url:
      'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&h=600&fit=crop',
    servings: 2,
    categories: [],
    ingredients: [],
    steps: [],
  },
  {
    id: '10',
    user_id: 'user-5',
    title: 'Grilled Salmon',
    description: 'Pan-seared salmon with lemon butter sauce',
    thumbnail_url:
      'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&h=600&fit=crop',
    cooking_time: 20,
    servings: 2,
    categories: [],
    ingredients: [],
    steps: [],
  },
  {
    id: '11',
    user_id: 'user-6',
    title: 'Chicken Teriyaki Bowl',
    thumbnail_url:
      'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop',
    cooking_time: 30,
    servings: 3,
    categories: [],
    ingredients: [],
    steps: [],
  },
  {
    id: '12',
    user_id: 'user-6',
    title: 'Vegetable Stir Fry',
    description: 'Colorful mixed vegetables with soy sauce',
    thumbnail_url:
      'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&h=600&fit=crop',
    cooking_time: 15,
    categories: [],
    ingredients: [],
    steps: [],
  },
  {
    id: '13',
    user_id: 'user-7',
    title: 'Beef Burger',
    description: 'Juicy beef patty with fresh toppings',
    thumbnail_url:
      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&h=600&fit=crop',
    cooking_time: 25,
    servings: 4,
    categories: [],
    ingredients: [],
    steps: [],
  },
  {
    id: '14',
    user_id: 'user-7',
    title: 'Margherita Pizza',
    thumbnail_url:
      'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&h=600&fit=crop',
    cooking_time: 40,
    servings: 6,
    categories: [],
    ingredients: [],
    steps: [],
  },
  {
    id: '15',
    user_id: 'user-8',
    title: 'Avocado Toast',
    description: 'Creamy avocado on toasted sourdough',
    thumbnail_url:
      'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&h=600&fit=crop',
    cooking_time: 5,
    servings: 1,
    categories: [],
    ingredients: [],
    steps: [],
  },
];
