import type { Recipe, RecipeCategory } from './types';

/**
 * 상황별 카테고리 목업 데이터
 */
export const mockSituationCategories: RecipeCategory[] = [
  { type: 'situation', code: 'daily', name: '일상' },
  { type: 'situation', code: 'speed', name: '초스피드' },
  { type: 'situation', code: 'guest', name: '손님접대' },
  { type: 'situation', code: 'solo', name: '혼밥' },
  { type: 'situation', code: 'diet', name: '다이어트' },
  { type: 'situation', code: 'bento', name: '도시락' },
  { type: 'situation', code: 'snack', name: '술안주/야식' },
  { type: 'situation', code: 'camping', name: '캠핑/나들이' },
  { type: 'situation', code: 'healing', name: '해장/보양' },
  { type: 'situation', code: 'baby', name: '이유식/키즈' },
  { type: 'situation', code: 'holiday', name: '명절' },
  { type: 'situation', code: 'etc', name: '기타' },
];

/**
 * 장르/나라별 카테고리 목업 데이터
 */
export const mockCuisineCategories: RecipeCategory[] = [
  { type: 'cuisine', code: 'korean', name: '한식' },
  { type: 'cuisine', code: 'bunsik', name: '분식' },
  { type: 'cuisine', code: 'western', name: '양식' },
  { type: 'cuisine', code: 'mexican', name: '멕시칸' },
  { type: 'cuisine', code: 'chinese', name: '중식' },
  { type: 'cuisine', code: 'japanese', name: '일식' },
  { type: 'cuisine', code: 'asian', name: '동남아식' },
  { type: 'cuisine', code: 'fusion', name: '퓨전' },
  { type: 'cuisine', code: 'etc', name: '기타' },
];

/**
 * 요리 종류별 카테고리 목업 데이터
 */
export const mockDishTypeCategories: RecipeCategory[] = [
  { type: 'dishType', code: 'rice', name: '밥/죽' },
  { type: 'dishType', code: 'noodle', name: '면요리' },
  { type: 'dishType', code: 'soup', name: '국/탕' },
  { type: 'dishType', code: 'stew', name: '찌개/전골' },
  { type: 'dishType', code: 'salad', name: '샐러드/무침' },
  { type: 'dishType', code: 'main_dish', name: '메인반찬' },
  { type: 'dishType', code: 'bread', name: '샌드위치/토스트' },
  { type: 'dishType', code: 'side_dish', name: '밑반찬/김치' },
  { type: 'dishType', code: 'dessert', name: '디저트/베이킹' },
  { type: 'dishType', code: 'sauce', name: '양념/소스/잼' },
  { type: 'dishType', code: 'drink', name: '음료/차' },
  { type: 'dishType', code: 'etc', name: '기타' },
];

/**
 * 모든 카테고리 목업 데이터
 */
export const mockAllCategories: RecipeCategory[] = [
  ...mockSituationCategories,
  ...mockCuisineCategories,
  ...mockDishTypeCategories,
];

/**
 * 테스트 및 개발용 목업 레시피 데이터
 */
export const mockRecipes: Recipe[] = [
  {
    id: '1',
    user_id: 'user-1',
    title: '바질 토마토 파스타',
    description: '신선한 토마토와 바질을 곁들인 클래식 이탈리아 파스타',
    thumbnail_url:
      'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&h=600&fit=crop',
    cooking_time: 15,
    servings: 2,
    categories: [
      { type: 'situation', code: 'daily', name: '일상' },
      { type: 'cuisine', code: 'western', name: '양식' },
      { type: 'dishType', code: 'noodle', name: '면요리' },
    ],
    ingredients: [
      { name: '스파게티 면', amount: '200', unit: 'g' },
      { name: '방울토마토', amount: '15', unit: '개' },
      { name: '신선한 바질', amount: '1', unit: '줌' },
      { name: '마늘', amount: '3', unit: '쪽' },
      { name: '올리브유', amount: '3', unit: 'T' },
      { name: '소금', amount: '약간' },
      { name: '후추', amount: '약간' },
      { name: '파마산 치즈', amount: '2', unit: 'T' },
    ],
    steps: [
      { step: 1, description: '끓는 물에 소금을 넣고 스파게티 면을 삶습니다.' },
      {
        step: 2,
        description: '마늘은 얇게 슬라이스하고, 방울토마토는 반으로 자릅니다.',
      },
      {
        step: 3,
        description: '팬에 올리브유를 두르고 마늘을 볶아 향을 냅니다.',
      },
      { step: 4, description: '방울토마토를 넣고 중불에서 5분간 볶습니다.' },
      { step: 5, description: '삶은 면과 면수 2큰술을 넣고 잘 섞습니다.' },
      { step: 6, description: '소금, 후추로 간하고 바질을 넣습니다.' },
      { step: 7, description: '접시에 담고 파마산 치즈를 뿌려 완성합니다.' },
    ],
    is_public: true,
    view_count: 156,
    favorite_count: 23,
    tags: ['파스타', '양식', '토마토', '바질', '간단'],
    created_at: new Date('2024-01-15'),
    updated_at: new Date('2024-01-15'),
  },
  {
    id: '2',
    user_id: 'user-1',
    title: '올리브 알리오 올리오',
    description: '지중해풍 풍미를 담은 심플한 마늘 올리브유 파스타',
    thumbnail_url:
      'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&h=600&fit=crop',
    cooking_time: 15,
    servings: 2,
    categories: [
      { type: 'situation', code: 'speed', name: '초스피드' },
      { type: 'cuisine', code: 'western', name: '양식' },
      { type: 'dishType', code: 'noodle', name: '면요리' },
    ],
    ingredients: [
      { name: '스파게티 면', amount: '200', unit: 'g' },
      { name: '마늘', amount: '5', unit: '쪽' },
      { name: '올리브유', amount: '5', unit: 'T' },
      { name: '페퍼론치노', amount: '2', unit: '개' },
      { name: '파슬리', amount: '약간' },
      { name: '소금', amount: '약간' },
      { name: '블랙올리브', amount: '10', unit: '개' },
    ],
    steps: [
      {
        step: 1,
        description: '끓는 물에 소금을 넣고 스파게티를 알덴테로 삶습니다.',
      },
      {
        step: 2,
        description: '마늘은 얇게 슬라이스하고, 페퍼론치노는 잘게 썹니다.',
      },
      {
        step: 3,
        description: '팬에 올리브유를 두르고 약불에서 마늘을 볶습니다.',
      },
      { step: 4, description: '페퍼론치노와 올리브를 넣고 향을 냅니다.' },
      { step: 5, description: '삶은 면과 면수를 넣고 잘 섞습니다.' },
      { step: 6, description: '파슬리를 뿌려 완성합니다.' },
    ],
    is_public: true,
    view_count: 89,
    favorite_count: 15,
    tags: ['파스타', '양식', '마늘', '올리브', '초스피드'],
    created_at: new Date('2024-01-20'),
    updated_at: new Date('2024-01-20'),
  },
  {
    id: '3',
    user_id: 'user-2',
    title: '볼로네제 파스타',
    description: '진한 미트소스와 펜네 파스타',
    thumbnail_url:
      'https://images.unsplash.com/photo-1598866594230-a7c12756260f?w=800&h=600&fit=crop',
    cooking_time: 15,
    servings: 4,
    categories: [
      { type: 'situation', code: 'guest', name: '손님접대' },
      { type: 'cuisine', code: 'western', name: '양식' },
      { type: 'dishType', code: 'noodle', name: '면요리' },
    ],
    ingredients: [
      { name: '펜네 파스타', amount: '300', unit: 'g' },
      { name: '소고기 간 것', amount: '250', unit: 'g' },
      { name: '양파', amount: '1', unit: '개' },
      { name: '당근', amount: '1/2', unit: '개' },
      { name: '셀러리', amount: '1', unit: '대' },
      { name: '토마토 소스', amount: '400', unit: 'ml' },
      { name: '레드와인', amount: '100', unit: 'ml' },
      { name: '올리브유', amount: '2', unit: 'T' },
      { name: '소금', amount: '약간' },
      { name: '후추', amount: '약간' },
    ],
    steps: [
      { step: 1, description: '양파, 당근, 셀러리를 잘게 다집니다.' },
      { step: 2, description: '팬에 올리브유를 두르고 다진 야채를 볶습니다.' },
      { step: 3, description: '소고기를 넣고 갈색이 될 때까지 볶습니다.' },
      { step: 4, description: '레드와인을 넣고 알코올을 날립니다.' },
      { step: 5, description: '토마토 소스를 넣고 약불에서 20분간 졸입니다.' },
      { step: 6, description: '펜네를 삶아 소스와 잘 버무립니다.' },
      { step: 7, description: '접시에 담고 파마산 치즈를 뿌려 완성합니다.' },
    ],
    is_public: true,
    view_count: 234,
    favorite_count: 45,
    tags: ['파스타', '양식', '볼로네제', '소고기', '손님접대'],
    created_at: new Date('2024-02-01'),
    updated_at: new Date('2024-02-01'),
  },
  {
    id: '4',
    user_id: 'user-2',
    title: '까르보나라',
    description: '베이컨과 계란으로 만든 크리미한 로마식 파스타',
    thumbnail_url:
      'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&h=600&fit=crop',
    cooking_time: 15,
    servings: 2,
    categories: [
      { type: 'situation', code: 'daily', name: '일상' },
      { type: 'cuisine', code: 'western', name: '양식' },
      { type: 'dishType', code: 'noodle', name: '면요리' },
    ],
    ingredients: [
      { name: '스파게티 면', amount: '200', unit: 'g' },
      { name: '베이컨', amount: '100', unit: 'g' },
      { name: '달걀 노른자', amount: '3', unit: '개' },
      { name: '파마산 치즈', amount: '50', unit: 'g' },
      { name: '블랙 페퍼', amount: '충분히' },
      { name: '소금', amount: '약간' },
      { name: '마늘', amount: '2', unit: '쪽' },
    ],
    steps: [
      { step: 1, description: '끓는 물에 소금을 넣고 스파게티를 삶습니다.' },
      {
        step: 2,
        description: '볼에 달걀 노른자, 파마산 치즈, 블랙 페퍼를 섞습니다.',
      },
      { step: 3, description: '베이컨과 마늘을 팬에서 바삭하게 볶습니다.' },
      { step: 4, description: '불을 끄고 삶은 면을 팬에 넣습니다.' },
      { step: 5, description: '달걀 치즈 혼합물을 넣고 재빨리 섞습니다.' },
      { step: 6, description: '면수를 조금씩 넣어 농도를 맞춥니다.' },
      { step: 7, description: '블랙 페퍼를 듬뿍 뿌려 완성합니다.' },
    ],
    is_public: true,
    view_count: 178,
    favorite_count: 38,
    tags: ['파스타', '양식', '까르보나라', '베이컨', '크리미'],
    created_at: new Date('2024-02-10'),
    updated_at: new Date('2024-02-10'),
  },
  {
    id: '5',
    user_id: 'user-3',
    title: '알프레도 파스타',
    thumbnail_url:
      'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=800&h=600&fit=crop',
    cooking_time: 20,
    servings: 3,
    categories: [
      { type: 'situation', code: 'daily', name: '일상' },
      { type: 'cuisine', code: 'western', name: '양식' },
      { type: 'dishType', code: 'noodle', name: '면요리' },
    ],
    ingredients: [
      { name: '페투치네 면', amount: '250', unit: 'g' },
      { name: '생크림', amount: '200', unit: 'ml' },
      { name: '버터', amount: '50', unit: 'g' },
      { name: '파마산 치즈', amount: '80', unit: 'g' },
      { name: '마늘', amount: '3', unit: '쪽' },
      { name: '소금', amount: '약간' },
      { name: '후추', amount: '약간' },
      { name: '파슬리', amount: '약간' },
    ],
    steps: [
      { step: 1, description: '페투치네 면을 삶아 준비합니다.' },
      { step: 2, description: '팬에 버터를 녹이고 다진 마늘을 볶습니다.' },
      { step: 3, description: '생크림을 넣고 약불에서 저어줍니다.' },
      { step: 4, description: '파마산 치즈를 넣고 녹을 때까지 섞습니다.' },
      { step: 5, description: '삶은 면을 넣고 소스와 잘 버무립니다.' },
      { step: 6, description: '소금, 후추로 간을 맞춥니다.' },
      { step: 7, description: '파슬리를 뿌려 완성합니다.' },
    ],
    is_public: false,
    view_count: 45,
    favorite_count: 8,
    tags: ['파스타', '양식', '알프레도', '크림', '치즈'],
    created_at: new Date('2024-02-15'),
    updated_at: new Date('2024-02-15'),
  },
  {
    id: '6',
    user_id: 'user-3',
    title: '해산물 마리나라 스파게티',
    description: '토마토소스를 곁들인 신선한 해산물 파스타',
    thumbnail_url:
      'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&h=600&fit=crop',
    cooking_time: 25,
    categories: [
      { type: 'situation', code: 'guest', name: '손님접대' },
      { type: 'cuisine', code: 'western', name: '양식' },
      { type: 'dishType', code: 'noodle', name: '면요리' },
    ],
    ingredients: [
      { name: '스파게티 면', amount: '250', unit: 'g' },
      { name: '새우', amount: '10', unit: '마리' },
      { name: '홍합', amount: '8', unit: '개' },
      { name: '오징어', amount: '1', unit: '마리' },
      { name: '토마토 소스', amount: '300', unit: 'ml' },
      { name: '마늘', amount: '4', unit: '쪽' },
      { name: '화이트와인', amount: '50', unit: 'ml' },
      { name: '올리브유', amount: '3', unit: 'T' },
      { name: '파슬리', amount: '약간' },
    ],
    steps: [
      { step: 1, description: '해산물을 깨끗이 손질합니다.' },
      { step: 2, description: '팬에 올리브유와 마늘을 볶아 향을 냅니다.' },
      { step: 3, description: '해산물을 넣고 화이트와인으로 볶습니다.' },
      { step: 4, description: '토마토 소스를 넣고 10분간 끓입니다.' },
      { step: 5, description: '삶은 스파게티를 넣고 잘 섞습니다.' },
      { step: 6, description: '파슬리를 뿌려 완성합니다.' },
    ],
    is_public: true,
    view_count: 67,
    favorite_count: 12,
    tags: ['파스타', '양식', '해산물', '마리나라', '손님접대'],
    created_at: new Date('2024-02-20'),
    updated_at: new Date('2024-02-20'),
  },
  {
    id: '7',
    user_id: 'user-4',
    title: '페스토 파스타',
    description: '잣과 함께하는 생동감 넘치는 바질 페스토',
    thumbnail_url:
      'https://images.unsplash.com/photo-1595295333158-4742f28fbd85?w=800&h=600&fit=crop',
    cooking_time: 10,
    servings: 2,
    categories: [
      { type: 'situation', code: 'speed', name: '초스피드' },
      { type: 'cuisine', code: 'western', name: '양식' },
      { type: 'dishType', code: 'noodle', name: '면요리' },
    ],
    ingredients: [
      { name: '스파게티 면', amount: '200', unit: 'g' },
      { name: '바질 페스토 소스', amount: '100', unit: 'g' },
      { name: '방울토마토', amount: '10', unit: '개' },
      { name: '잣', amount: '2', unit: 'T' },
      { name: '파마산 치즈', amount: '30', unit: 'g' },
      { name: '올리브유', amount: '2', unit: 'T' },
      { name: '소금', amount: '약간' },
    ],
    steps: [
      { step: 1, description: '스파게티를 알덴테로 삶습니다.' },
      { step: 2, description: '방울토마토를 반으로 자릅니다.' },
      { step: 3, description: '삶은 면에 페스토 소스를 넣고 섞습니다.' },
      { step: 4, description: '방울토마토와 잣을 넣습니다.' },
      { step: 5, description: '올리브유를 두르고 잘 버무립니다.' },
      { step: 6, description: '파마산 치즈를 뿌려 완성합니다.' },
    ],
    is_public: true,
    view_count: 123,
    favorite_count: 28,
    tags: ['파스타', '양식', '페스토', '바질', '초스피드'],
    created_at: new Date('2024-02-25'),
    updated_at: new Date('2024-02-25'),
  },
  {
    id: '8',
    user_id: 'user-4',
    title: '버섯 리조또',
    thumbnail_url:
      'https://images.unsplash.com/photo-1476124369491-f51aae654b1d?w=800&h=600&fit=crop',
    cooking_time: 35,
    servings: 4,
    categories: [
      { type: 'situation', code: 'guest', name: '손님접대' },
      { type: 'cuisine', code: 'western', name: '양식' },
      { type: 'dishType', code: 'rice', name: '밥/죽' },
    ],
    ingredients: [
      { name: '아보리오 쌀', amount: '300', unit: 'g' },
      { name: '버섯', amount: '200', unit: 'g' },
      { name: '양파', amount: '1', unit: '개' },
      { name: '화이트와인', amount: '100', unit: 'ml' },
      { name: '육수', amount: '1', unit: 'L' },
      { name: '버터', amount: '40', unit: 'g' },
      { name: '파마산 치즈', amount: '60', unit: 'g' },
      { name: '올리브유', amount: '2', unit: 'T' },
      { name: '소금', amount: '약간' },
      { name: '후추', amount: '약간' },
    ],
    steps: [
      { step: 1, description: '양파를 다지고 버섯을 슬라이스합니다.' },
      {
        step: 2,
        description: '팬에 버터와 올리브유를 두르고 양파를 볶습니다.',
      },
      { step: 3, description: '쌀을 넣고 투명해질 때까지 볶습니다.' },
      { step: 4, description: '화이트와인을 넣고 졸입니다.' },
      { step: 5, description: '육수를 국자씩 넣어가며 저어줍니다.' },
      { step: 6, description: '버섯을 넣고 쌀이 익을 때까지 계속 저어줍니다.' },
      {
        step: 7,
        description: '불을 끄고 파마산 치즈와 버터를 넣어 완성합니다.',
      },
    ],
    is_public: true,
    view_count: 198,
    favorite_count: 42,
    tags: ['리조또', '양식', '버섯', '손님접대', '이탈리안'],
    created_at: new Date('2024-03-01'),
    updated_at: new Date('2024-03-01'),
  },
  {
    id: '9',
    user_id: 'user-5',
    title: '시저 샐러드',
    description: '파마산과 크루통을 곁들인 아삭한 로메인 샐러드',
    thumbnail_url:
      'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&h=600&fit=crop',
    servings: 2,
    categories: [
      { type: 'situation', code: 'diet', name: '다이어트' },
      { type: 'cuisine', code: 'western', name: '양식' },
      { type: 'dishType', code: 'salad', name: '샐러드/무침' },
    ],
    ingredients: [
      { name: '로메인 상추', amount: '1', unit: '포기' },
      { name: '크루통', amount: '1', unit: '컵' },
      { name: '파마산 치즈', amount: '50', unit: 'g' },
      { name: '시저 드레싱', amount: '80', unit: 'ml' },
      { name: '베이컨', amount: '4', unit: '줄' },
      { name: '레몬즙', amount: '1', unit: 'T' },
      { name: '블랙 페퍼', amount: '약간' },
    ],
    steps: [
      {
        step: 1,
        description: '로메인 상추를 깨끗이 씻어 한입 크기로 자릅니다.',
      },
      { step: 2, description: '베이컨을 바삭하게 구워 잘게 부숩니다.' },
      { step: 3, description: '볼에 상추를 담고 시저 드레싱을 넣습니다.' },
      { step: 4, description: '크루통과 베이컨을 올립니다.' },
      { step: 5, description: '파마산 치즈를 뿌리고 레몬즙을 뿌립니다.' },
      { step: 6, description: '블랙 페퍼로 마무리합니다.' },
    ],
    is_public: true,
    view_count: 92,
    favorite_count: 18,
    tags: ['샐러드', '양식', '다이어트', '시저', '건강식'],
    created_at: new Date('2024-03-05'),
    updated_at: new Date('2024-03-05'),
  },
  {
    id: '10',
    user_id: 'user-5',
    title: '구운 연어',
    description: '레몬 버터 소스를 곁들인 팬 시어 연어',
    thumbnail_url:
      'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&h=600&fit=crop',
    cooking_time: 20,
    servings: 2,
    categories: [
      { type: 'situation', code: 'guest', name: '손님접대' },
      { type: 'cuisine', code: 'western', name: '양식' },
      { type: 'dishType', code: 'main_dish', name: '메인반찬' },
    ],
    ingredients: [
      { name: '연어', amount: '2', unit: '조각' },
      { name: '버터', amount: '30', unit: 'g' },
      { name: '레몬', amount: '1', unit: '개' },
      { name: '마늘', amount: '2', unit: '쪽' },
      { name: '파슬리', amount: '약간' },
      { name: '소금', amount: '약간' },
      { name: '후추', amount: '약간' },
      { name: '올리브유', amount: '1', unit: 'T' },
    ],
    steps: [
      { step: 1, description: '연어에 소금과 후추로 밑간합니다.' },
      { step: 2, description: '팬에 올리브유를 두르고 중불로 가열합니다.' },
      { step: 3, description: '연어를 껍질 면부터 3-4분간 굽습니다.' },
      { step: 4, description: '뒤집어서 2-3분 더 굽습니다.' },
      { step: 5, description: '버터, 다진 마늘, 레몬즙을 넣고 끼얹어줍니다.' },
      { step: 6, description: '파슬리를 뿌려 완성합니다.' },
    ],
    is_public: true,
    view_count: 312,
    favorite_count: 67,
    tags: ['연어', '양식', '손님접대', '레몬버터', '메인요리'],
    created_at: new Date('2024-03-10'),
    updated_at: new Date('2024-03-10'),
  },
  {
    id: '11',
    user_id: 'user-6',
    title: '데리야끼 치킨 덮밥',
    thumbnail_url:
      'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop',
    cooking_time: 30,
    servings: 3,
    categories: [
      { type: 'situation', code: 'solo', name: '혼밥' },
      { type: 'cuisine', code: 'japanese', name: '일식' },
      { type: 'dishType', code: 'rice', name: '밥/죽' },
    ],
    ingredients: [
      { name: '밥', amount: '1', unit: '공기' },
      { name: '닭가슴살', amount: '150', unit: 'g' },
      { name: '데리야끼 소스', amount: '100', unit: 'ml' },
      { name: '양파', amount: '1/2', unit: '개' },
      { name: '파프리카', amount: '1/2', unit: '개' },
      { name: '브로콜리', amount: '50', unit: 'g' },
      { name: '참기름', amount: '1', unit: 't' },
      { name: '통깨', amount: '약간' },
      { name: '김', amount: '약간' },
    ],
    steps: [
      { step: 1, description: '닭가슴살을 한입 크기로 자릅니다.' },
      { step: 2, description: '야채를 먹기 좋은 크기로 썹니다.' },
      {
        step: 3,
        description: '팬에 닭고기를 볶다가 데리야끼 소스를 넣습니다.',
      },
      { step: 4, description: '야채를 넣고 함께 볶습니다.' },
      { step: 5, description: '밥 위에 담고 참기름을 뿌립니다.' },
      { step: 6, description: '통깨와 김을 올려 완성합니다.' },
    ],
    is_public: true,
    view_count: 145,
    favorite_count: 31,
    tags: ['덮밥', '일식', '데리야끼', '치킨', '혼밥'],
    created_at: new Date('2024-03-15'),
    updated_at: new Date('2024-03-15'),
  },
  {
    id: '12',
    user_id: 'user-6',
    title: '야채 볶음',
    description: '간장으로 볶은 알록달록 모둠 채소',
    thumbnail_url:
      'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&h=600&fit=crop',
    cooking_time: 15,
    categories: [
      { type: 'situation', code: 'diet', name: '다이어트' },
      { type: 'cuisine', code: 'asian', name: '동남아식' },
      { type: 'dishType', code: 'main_dish', name: '메인반찬' },
    ],
    ingredients: [
      { name: '브로콜리', amount: '100', unit: 'g' },
      { name: '당근', amount: '1', unit: '개' },
      { name: '파프리카', amount: '1', unit: '개' },
      { name: '양파', amount: '1', unit: '개' },
      { name: '버섯', amount: '100', unit: 'g' },
      { name: '간장', amount: '2', unit: 'T' },
      { name: '굴소스', amount: '1', unit: 'T' },
      { name: '마늘', amount: '3', unit: '쪽' },
      { name: '식용유', amount: '2', unit: 'T' },
    ],
    steps: [
      { step: 1, description: '모든 야채를 먹기 좋은 크기로 썹니다.' },
      { step: 2, description: '브로콜리를 데쳐 준비합니다.' },
      { step: 3, description: '팬을 달궈 식용유와 마늘을 볶습니다.' },
      { step: 4, description: '단단한 야채부터 넣어 볶습니다.' },
      { step: 5, description: '간장과 굴소스로 양념합니다.' },
      { step: 6, description: '모든 야채가 익으면 완성입니다.' },
    ],
    is_public: true,
    view_count: 78,
    favorite_count: 14,
    tags: ['볶음', '다이어트', '야채', '건강식', '동남아'],
    created_at: new Date('2024-03-20'),
    updated_at: new Date('2024-03-20'),
  },
  {
    id: '13',
    user_id: 'user-7',
    title: '비프 버거',
    description: '신선한 토핑을 곁들인 육즙 가득 소고기 패티',
    thumbnail_url:
      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&h=600&fit=crop',
    cooking_time: 25,
    servings: 4,
    categories: [
      { type: 'situation', code: 'daily', name: '일상' },
      { type: 'cuisine', code: 'western', name: '양식' },
      { type: 'dishType', code: 'bread', name: '샌드위치/토스트' },
    ],
    ingredients: [
      { name: '소고기 간 것', amount: '300', unit: 'g' },
      { name: '햄버거 번', amount: '4', unit: '개' },
      { name: '양상추', amount: '4', unit: '장' },
      { name: '토마토', amount: '1', unit: '개' },
      { name: '양파', amount: '1/2', unit: '개' },
      { name: '치즈', amount: '4', unit: '장' },
      { name: '피클', amount: '적당량' },
      { name: '소금', amount: '약간' },
      { name: '후추', amount: '약간' },
      { name: '버거 소스', amount: '적당량' },
    ],
    steps: [
      {
        step: 1,
        description: '소고기에 소금, 후추를 넣고 패티 4개를 만듭니다.',
      },
      { step: 2, description: '양상추, 토마토, 양파를 슬라이스합니다.' },
      { step: 3, description: '팬에 패티를 앞뒤로 3-4분씩 굽습니다.' },
      { step: 4, description: '치즈를 패티 위에 올려 녹입니다.' },
      { step: 5, description: '번에 소스를 바르고 야채를 올립니다.' },
      { step: 6, description: '패티를 올리고 피클을 얹어 완성합니다.' },
    ],
    is_public: true,
    view_count: 267,
    favorite_count: 52,
    tags: ['버거', '양식', '소고기', '홈메이드', '파티'],
    created_at: new Date('2024-03-25'),
    updated_at: new Date('2024-03-25'),
  },
  {
    id: '14',
    user_id: 'user-7',
    title: '마르게리타 피자',
    thumbnail_url:
      'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&h=600&fit=crop',
    cooking_time: 40,
    servings: 6,
    categories: [
      { type: 'situation', code: 'guest', name: '손님접대' },
      { type: 'cuisine', code: 'western', name: '양식' },
      { type: 'dishType', code: 'main_dish', name: '메인반찬' },
    ],
    ingredients: [
      { name: '피자 도우', amount: '1', unit: '판' },
      { name: '토마토 소스', amount: '150', unit: 'ml' },
      { name: '모짜렐라 치즈', amount: '200', unit: 'g' },
      { name: '방울토마토', amount: '10', unit: '개' },
      { name: '신선한 바질', amount: '1', unit: '줌' },
      { name: '올리브유', amount: '2', unit: 'T' },
      { name: '소금', amount: '약간' },
      { name: '마늘', amount: '2', unit: '쪽' },
    ],
    steps: [
      { step: 1, description: '오븐을 220도로 예열합니다.' },
      { step: 2, description: '도우에 토마토 소스를 고르게 펴 바릅니다.' },
      { step: 3, description: '모짜렐라 치즈를 올립니다.' },
      { step: 4, description: '방울토마토와 다진 마늘을 올립니다.' },
      { step: 5, description: '올리브유를 뿌리고 15-20분간 굽습니다.' },
      { step: 6, description: '신선한 바질을 올려 완성합니다.' },
    ],
    is_public: true,
    view_count: 189,
    favorite_count: 41,
    tags: ['피자', '양식', '마르게리타', '손님접대', '홈베이킹'],
    created_at: new Date('2024-04-01'),
    updated_at: new Date('2024-04-01'),
  },
  {
    id: '15',
    user_id: 'user-8',
    title: '아보카도 토스트',
    description: '사워도우 토스트 위의 크리미한 아보카도',
    thumbnail_url:
      'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&h=600&fit=crop',
    cooking_time: 5,
    servings: 1,
    categories: [
      { type: 'situation', code: 'speed', name: '초스피드' },
      { type: 'cuisine', code: 'western', name: '양식' },
      { type: 'dishType', code: 'bread', name: '샌드위치/토스트' },
    ],
    ingredients: [
      { name: '사워도우 빵', amount: '2', unit: '조각' },
      { name: '아보카도', amount: '1', unit: '개' },
      { name: '레몬즙', amount: '1', unit: 'T' },
      { name: '방울토마토', amount: '5', unit: '개' },
      { name: '소금', amount: '약간' },
      { name: '후추', amount: '약간' },
      { name: '올리브유', amount: '1', unit: 't' },
      { name: '칠리 플레이크', amount: '약간' },
    ],
    steps: [
      { step: 1, description: '빵을 토스터에 구워 바삭하게 만듭니다.' },
      {
        step: 2,
        description: '아보카도를 으깨고 레몬즙, 소금, 후추를 섞습니다.',
      },
      { step: 3, description: '토스트에 아보카도를 펴 바릅니다.' },
      { step: 4, description: '방울토마토를 슬라이스해 올립니다.' },
      { step: 5, description: '올리브유를 뿌리고 칠리 플레이크를 올립니다.' },
      { step: 6, description: '후추를 뿌려 완성합니다.' },
    ],
    is_public: true,
    view_count: 108,
    favorite_count: 22,
    tags: ['토스트', '양식', '아보카도', '초스피드', '브런치'],
    created_at: new Date('2024-04-05'),
    updated_at: new Date('2024-04-05'),
  },
];
